### ISSUE TITLE
Import failed using ssh

### ISSUE THREAD

**Issue by xnaveira** [theforeman/foreman_templates#14]
Hi,

I'm trying to import templates from a custom git repo.

When I run via https it works fine but then I need to enter the password:
```
sudo foreman-rake templates:sync repo="https://user@stash.domain.org/scm/xx/foreman-templates.git" prefix="pre-" --trace
```

I can clone the repo with git:
```
git clone ssh://git@stash.domain.org/xx/foreman-templates.git
```

But if I try to combine all of the above to be able to update the templates using the plugin and using a key instead for a password it happens the following:
```
sudo foreman-rake templates:sync repo="ssh://git@stash.domain.org/xx/foreman-templates.git" prefix="pre-" --trace
** Invoke templates:sync (first_time)
** Invoke environment (first_time)
** Execute environment
Workaround for RbVmomi may not work as ComputeResource is already loaded: ComputeResource
[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.
** Execute templates:sync
rake aborted!
Errno::ENOENT: No such file or directory - /tmp/d20150602-7732-dw9y0p
/usr/lib/ruby/1.9.1/fileutils.rb:696:in `lstat'
/usr/lib/ruby/1.9.1/fileutils.rb:696:in `remove_entry_secure'
/usr/share/foreman/vendor/ruby/1.9.1/gems/foreman_templates-1.5.0/lib/templates.rake:194:in `ensure in block (2 levels) in <top (required)>'
/usr/share/foreman/vendor/ruby/1.9.1/gems/foreman_templates-1.5.0/lib/templates.rake:194:in `block (2 levels) in <top (required)>'
/usr/share/foreman/vendor/ruby/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/usr/share/foreman/vendor/ruby/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/usr/share/foreman/vendor/ruby/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/usr/share/foreman/vendor/ruby/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/usr/share/foreman/vendor/ruby/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/share/foreman/vendor/ruby/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/share/foreman/vendor/ruby/1.9.1/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/usr/share/foreman/vendor/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/usr/share/foreman/vendor/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/share/foreman/vendor/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/usr/share/foreman/vendor/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/usr/share/foreman/vendor/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/usr/share/foreman/vendor/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/usr/share/foreman/vendor/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/usr/share/foreman/vendor/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/share/foreman/vendor/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/bin/rake1.9.1:32:in `<main>'
Tasks: TOP => templates:sync
```

Thanks.

X

**Comment by domcleal** [comment]
Try removing the `ssh://` prefix, it seems that this causes a problem.  Just using `git@github.com:theforeman/community-templates.git` (in my case) worked better.

I'll file a PR that fixes the error reporting.

**Comment by xnaveira** [comment]
@domcleal that works definitively better but then it still asks for my password, it seems that somehow it ignores the settings in my ~/.ssh/config file.

Is there a way to supply the identity file?

**Comment by domcleal** [comment]
You might need to up the SSH credentials under the "foreman" user, because `foreman-rake` actually calls `su` to change user to run rake tasks.  It's not going to pick up your SSH credentials.

**Comment by xnaveira** [comment]
Which user is it changing to?

**Comment by domcleal** [comment]
#15 fixes the error handling, so you'd at least see an error about cloning.

**Comment by xnaveira** [comment]
Thank you!
