### ISSUE TITLE
Please support export over ssh

### ISSUE THREAD

**Issue by hboetes** [theforeman/foreman_templates#42]
With my proposed patch I ran into the following problem while trying to export over ssh/git

```
foreman-rake templates:export repo="ssh://git@gitserver:/home/git/templates2.git" verbose=true
Successfully encrypted field for Setting::Auth oauth_consumer_key
Successfully decrypted field for Setting::Auth oauth_consumer_key
Successfully decrypted field for Setting::Auth oauth_consumer_key
Successfully decrypted field for Setting::Auth oauth_consumer_key
Successfully encrypted field for Setting::Auth oauth_consumer_secret
Successfully decrypted field for Setting::Auth oauth_consumer_secret
Successfully decrypted field for Setting::Auth oauth_consumer_secret
Successfully decrypted field for Setting::Auth oauth_consumer_secret
rake aborted!
Git::GitExecuteError: git '--git-dir=/tmp/d20170328-9946-1oln4r4/.git' '--work-tree=/tmp/d20170328-9946-1oln4r4' push 'origin' ''  2>&1:fatal: remote part of refspec is not a valid name in 
/usr/share/foreman/vendor/ruby/2.3.0/gems/git-1.3.0/lib/git/lib.rb:937:in `command'
/usr/share/foreman/vendor/ruby/2.3.0/gems/git-1.3.0/lib/git/lib.rb:742:in `push'
/usr/share/foreman/vendor/ruby/2.3.0/gems/git-1.3.0/lib/git/base.rb:329:in `push'
/usr/share/foreman/vendor/ruby/2.3.0/bundler/gems/foreman_templates-f7c15eafd844/app/services/foreman_templates/template_exporter.rb:50:in `export_to_git'
/usr/share/foreman/vendor/ruby/2.3.0/bundler/gems/foreman_templates-f7c15eafd844/app/services/foreman_templates/template_exporter.rb:9:in `export!'
/usr/share/foreman/vendor/ruby/2.3.0/bundler/gems/foreman_templates-f7c15eafd844/lib/tasks/foreman_templates_tasks.rake:43:in `block (2 levels) in <top (required)>'
Tasks: TOP => templates:export
(See full trace by running task with --trace)
```

**Comment by kjelle** [comment]
With foreman_templates v3.1.0 we could use "git@gitlab.example.com:group/repo".
If I try this with v4.0.1 foreman_templates thinks we'r using a local directory.

**Comment by ares** [comment]
ssh:// is now supported, will be part of next 4.0.z release
